let marks =100;
if(marks >=90 && marks <=100)
    console.log("Your grade is A");
else if(marks >=80 && marks <=89)
    console.log("Your grade is B");
else if(marks >=70 && marks <=79)
    console.log("Your grade is C");
else if(marks >=60 && marks <=69)
    console.log("Your grade is D");
else if(marks >=0 && marks <=59)
    console.log("Your grade is E");

else
    console.log("invalid input");

